spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to NichBank accounts related PROD APIs"
  contactDetails:
    name: "Dwight Schrutte- Prod Lead"
    email: "{cipher}789560b2983c10edd3bafeb5ae2fa77317d1850a7c539781122620b7aaffb26eea35842c45dd6942f945948323faf053"
  onCallSupport:
    - (502) 100 1001
    - (502) 201 2011
